version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk17
branches:
  only:
    - develop
    - support/4.1.x
    - support/4.0.x
    - master
cache:
  directories:
  - "$HOME/.m2"
notifications:
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
  - mkdir -p $HOME/.m2
  - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
  global:
    - secure: "NLYC2ccIpUzHFdpisQ45MlJA9zPgiLZUw6xMlGwlcRRIP9HD4cjZsQlifaNFDz55ThHraQLDMohkiNXwMVh76oLLiwKzsiDIQXCOQtw8pfYfiBp3sZIM0m/E75mAxSlm1P6679XohCMpsZo+5lYiwBlosU1HQYvmyg3+Mo5JmntZl+iqRgqoeXw7X4rY3dogDTEHfVrjCgHfWnI48PLRxs01rv9KI1sORz+E+EsXfxwxRp6+zPwJop1792EPCKmPb0DoZAEsAcP/UIM8TI6xW9M4rYwqGHaZuFvrmwSZTrjZ1eFoQTJR5rVikqwmtMv7sWzVnIOYPWT+2819F9bOg7ZBwFXJLBe1TeWYEzfeqR/ZxvKL33l3JSe4+eEhSxxROFIOxjellDirzwuLsfxQ9MBE/6BycKtd/h3AxMFUc3qq5VKFy/nDJeQZ+5u0tG4FQtfxKfBgBnilTtVje6v2C3ZimrGr11HxCIyrQdo7Zpf2BCnc10IJMFMEjDy/tDyeaM6OyOtKuCfUTs+PU8lgF7Vqy9nDCVhyHvOttsIPzKA9dtpARlQIaadEFBWlE7Q2kPxH6Dtiu9oo4sGA/fcaux+9vNsfLPpaKNAITNtIQYhnPmyL+0lgUsYH06IyUsgn2YF+dt1Xxy58JRg8V/iPy7yECjEESA+AUSxImGlgTmw="
    - secure: "fA/VPsGISF82PtQSL1Fp+SEG/V8osSp1Q3bwg38smc6GdbFpLiqa/6vSGDIaSU8bSVIqL2vzMNJp9ktNDXdnKUnLT9t/8no2ZZK56kATvMq+/NzWMWb+IHy53exhkbvTOi3YuoEhA2YSkVV40uRuZ/zzQZX53R5ua229gkxIIFxnyi3YqLJxCLaoY6flNpneNwoISGzNB10kfvJiJZvyc3IGQJwt3PcSusGI3GIjSKD1BrQ6Ua50EzWnBgdsY+bN3dUz76O3G10EJ4ApwnDs2zKYAP1/R9hiHjRp1NCVpNPrbsbnLvDipIvVCwn+LBIvCorW5J0249m0iOHxQurbsYpwiDpOH0SlyGnDyBGnjmFJgBoc2YF0WTpAPmFTeccFzPL6vZh2GdQ+bka6hrrA/JQm/R3O7ZxtWrxtU7t3d+oEW4umpoQyNPU4/s/aRGVUGNwYHok0bDz4fahp3vogHb0177sr6/2B2dUVZ9XG59s5Fi3sDsL4PHwRseJjGU5+0DZnQxrGgQvK4X96xefTFtwC7uta6Y/rHimKRg+9Sej5LGAVC6bU4bzNza/tR2TGVtZPK2eAqhiVb3ZcPxsLUfW/UN9u6QulT4KpopEiw++BrcpnOo6oQ/Gms+mxdSrFHOCp8G6/UZA9sPlo8RxSaRAOmiTdYK2BgpEnPU7x0ds="
