version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
- openjdk17
branches:
  only:
  - develop
  - support/.*
  - master
cache:
  directories:
  - "$HOME/.m2"
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
  - mkdir -p $HOME/.m2
  - cp .travis-settings.xml $HOME/.m2/settings.xml
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c  "mvn -DskipTests deploy
  --settings .travis-settings.xml";  fi
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn -DskipTests clean
  install" ;fi
env:
  global:
  - secure: KiFsKr7SrJwYQw2CW1VjEZNjOBzjExiH9HDmcrGKExfHhnt2IMepR5Vg/npsSmC7nNV4b1mSqlIbeNFfGmrxcWMN8bBNs94l4P+Xl4aM1f4Q9XMozPyeBev8lLAUWR/esx6yIv3Fppyy/cDEunZyQA9KksatVhn+OoD08Gzx4ElBArvZgEKnenwuvbJLN2a86xFeZuJXpyUMK/U5h/44nanps32yg7Uu1wLe57ApM5Y1umGsTHV4jhqLtHGKTCjLc/GR7o7zcqjMUpeLYmu3RFR9bY5vw6rNGXbWq530cp6xdqSMIFYHoIJoicAr9fh9NtFFEMg+DGmcaGsf9uhaqmvo5GfUedxqeXJF1AT7hzi2uZDaW701LVx6dCNrTfaKqrPwmSVgZNY9zLf2fqW+4pH1uVGlijWQK0XbC4zPg3Qq5Ii+gdybRAcOjQ/jGnqfir4DhaiYBhvMy55Nd9v1unuaBbhK/Aei7ho4lRAzqQ6W1Gwg9SIrQE1tfbpgpzFrF2F4pt/v8yo+3KV9imIRfs5aJFjMIrmkTEAl+FyOs58fMhfpvRMdo7ARx/35Qg0dxsTcUbMstzU4bwPUV02McsCKpOFD2sAtbydwnL0K4JuPgtelrxhDC9XLKbLm2QeaQG56LCuXg5iIFR/Qq0r1KBD2htbIy6i3R3vyJk2bPO8=
  - secure: AUKx8wv4aSXp2YMYhIhSoh/oskNfpPFgYAZvJcxgdHKJHlIl6hRYlQRjJWKb5HM9bq5/eIO6Mbycb3Hm5VNhdPqe1q0+CfdDmRo+QaNz5gx5/Mt5MYBhDhM86WmzBq1LF+7EPXH3PTz6/q+cbeONIkxxByYFBdaJcM9uS9xhFVlg6UeE/AxL2PSqo9USeuBYoWbiOPS1EjgseB2WISVDol/wuy0vjMF8idGygTB5bvWtVITgh+jf37LXk2pBTs50pEav3tvSMh3ths1OVIygrUQo7wmmPFtkf5HqpDMZntHXRvPRUyct89pw1TwBT4yNpH/v3WaG+oBwf2e9HdcvWkL4JKh6l852hb2AUD5xCp0a/aUd20IV94DDS+cmuBj2Gt4bOZl5RfCaPaBrsi7mmP+Ke7fVs0lGAy/Hl0KGpNwoWQBKI6Bqb1v3qquyimw6GQnmlZTTcdDzZZxc8MF/E0WTTS1eti3ejFOBwKd6ocrjMm0dK17sRHuY7ijjISJgYsusPDB4aQ+6sZKr1SwYgdUdu/gc+WPO36zr3YqACNPC15/5DXqfmWkuLnXWGS/2eOOKH/qXdl7InaNgVZEF0ROVmoWS6GGINrucfx93jwSD7hjv875LnO6puOckG39K7bE18kcig/uoKucVPc0SZ9NbK+8pJIvCmnwDDHUdiSI=
