version: ~> 1.0
git:
  depth: 1
  quiet: true
language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - support/.*
  - master
cache:
  directories:
    - $HOME/.m2
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c  "mvn -DskipTests deploy
  --settings .travis-settings.xml";  fi
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn -DskipTests clean install"
  ;fi
env:
  global:
  - secure: lT0EuswTaffHEoFx9QJUJCqv3Ko+u3DW2H6OY9sDlQVkceiYYxqiCKJKhfjc9ZtnBeIQb4aQq4RZsuJnCIqhSGktWZx6epUEX0nndchCYe39cewpwXz8lI4qpqWPV8W0xH69DaquYO4GjBIxOk2CoTwinYr8aksY7S7c4SSx1pm0sP4M5bP0RE9f+S+bpzVot1hn/yq0/0XfNRdmOEP8ro/be+NIYTfi7bqqkIZELuJOBlvZlppV37vhxetfe/Wfbg0uy4meLCkMEteEFYwlxLqz2xf8bbSvLFjdfp0BNfODAsU0KndxUXI9PnKtPvIbBWdfbW9sSZDzB0AuQAYKdoMMlIPuqtY57vz8MCNup6QEqUtU6iTQwBBKOyKKOAcNf6+7ovvuLBMqi4VeQ9VDH6tyPDw7y9f/qBURRTBYTmR2ajEuNuQ0H9XzKeHTE2BB9sGpd9fdBtO36wUvLKjkuFWMS9Mi++StaID7IE1LYqg1jgNvL63sNVoXpdVuzNeEHr22neFcr8ZL5emeAMS62PPJXAQU+I4w+utzswz7uSSCChVSjS3cl75RKAGjD9em1pjy0Victtt2FQA2p1wBf4rq7Uu7yTdpqg7Ze26LV4dsD9KxKESU4rnz7PODDPUh0+w/H/kJ5JXiOxuTg9bAxXpLylj2ajGbHLGHk9yMMIc=
  - secure: F5vUom0nAaQJ71iulKrVh7aCe0JJi74YJ0iRVRqY9IZCJbm1uldnCUoZ1kngh5Hf00Tuo97dQB6N5BBR3eIoGUsDOOXZwyNpR+bAm2GTMcqeoTbtYAWa4J9X/AbfoyMonX+XTWoRpn2HqzyXHCYzEuOBNtbouXNfhV290ajgKt9a/7yYliyA5nCGQV3AN6dtRxNqrwldqwdttCiOrkV4MlzQB4FxE103y0Gu3YyAiFvbwDV189wEa15RzVdej5L4RyjTU8LgX/fe46Yba+9oznLpytBlwAuapjPZYLisbAq+zA1JMIgDgbgWxG5SEfafGHKDlQfbI88CHrqGl/N+I1rYnJ6JdMOesditA5KWlEx0m8QY/rQ0EW80xsNSHe56uFCdE4AC3SMZMpkSE0ktPU1yiX0IJf9LfR8Q5rwF6myo52HVuLIZ6FHINtb/fTPf5wTvBEypLTbawCJ/9w7rxePtoQmapQcFG/3YYEOXE6oZAnn+ZG0CYTUwrtElF2pf9Mt5pBDydPbk7rNZz8XySIDHCweSxe6AILtZ1LKfvxFTwlizwa0muJD137q4CNt7Og2+MYvc+Q6hXzkbtqKHvnnfIafY0+UyEJPuvvb7KR/IRaTdIgRt08oYcx/n7djuUmH/LAhxOdLd8yB6Ea8z7uZvwugd91NRe42YDlBHeCg=
