version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk17
branches:
  only:
    - develop
    - support/4.1.x
    - support/4.0.x
    - master
cache:
  directories:
  - "$HOME/.m2"
notifications:
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
  - mkdir -p $HOME/.m2
  - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy -DskipTests --settings .travis-settings.xml"; fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install -DskipTests"; fi
env:
  global:
    - secure: "eEER0sHFMFSpp89IK+Cej0BdIDTYnsZMUWMJBzEY5Gje8GrdhGnYVJKZuaADzToj2uMl78SKpb0HFib/59UJGtXspqBtcCQ1YoI75L2SaGz/qFbGXpxZWM2e/o5FdcG6EDE+GaRM8uqfC61rDSsZzZWahZ0dkv9OKaV8C2VrFzit2gwNMTFlZrnR8jGzOacEQqXNDLUDRYuKTbc+zvS0g17oWveEC6PPxUMEqlHEmuvG5t8NVgtkm8LiSOK/yv+8UQH//y6Ip8xY2AEpZeSW+E4X9YLzMfPjix28DIGWXefwY+vkQBDTlxgpYm73T4v+yYukbxihcgCRbV3WQkID54zaxKzy6lj8EvhIWuheW0DVTn5tZrw7ldvGXYSUaPjZFp6U+YVDvTqHscnpUfFQVxsIrz/iX9sploaxO0fW/PlfPKrbhKDh8B1neWSGc0+i92R0iNYnye7QKF73i6EU/cQpNRvWffwKjQ+I1n9tCX3bGtTnMLEtN6sY/pPk4v1zp3LVrZat4l57Y3hP9Jb1fqvqqxmUvJNckYpgksP4EWeifk3mEEmyIXbLJBU3K1N7jaydVqOVIu1RD+QpVcjmsYz+FBjUcrgViD+mQnGhQJu7MblzVAHmcnhjBeysASQWTjekgb8v0SE6rjoSoIGuBZyDUzFT7h6XojeZ+7NNwUE="
    - secure: "OSefiu0qNp9TsnNJXBp+KKPhyeFcLB+5uMDq1uYcIbx3kz9MGnBzJqwfJ3ALluQJBAUK8Y2t4bYwXrewP5u2jBeHs9WRIOP4+1Bf6T3nd4jLzqUUt8gHtY1wdWMGpUrzXVZOcInK63VDhsYezQN3UFd8w8Zw4k2ypUZ7eZfxiHUirwSPfe2DdYYsXZNyzOz/Cny0maCg+IP5jLEbuWXm4RJ2iBsfDdqSfwJ0o6SUGAVIIdt1p4Ww+UFjMFPFCi8ikRRNjoIc3b6C8I6tKv5eY5NskGP/jVkOV9waYgpLx2SilxhnwcGtE4lTufxWzKQeEje/Ub22yfpKU0nUaNwB5l/Tl8GovtkhjV34qy9vYXP5Xarg+upyRzJCINFHdu0hN1/DQKxfxNf9qQ7TQQMGG8g3/FStYRui7XdlY7QwaXFw34/gkM2dinqXEJegDb5hDDzWjpvNbQXK29r0cGzfyuvUNJRS/XCdM8bpvA6r9kLhJxGOFQei/vKPOyxDxAT2zsQSQPnlJ2bA+9IKg71zrMnrRJ4IXjO7Gnpdn0mqFVC59jITQebr4dph5ChR/Mh7IU9PnpAnn72KA1jA0pgZwo9zocPAiAMYrVgLowmaycIz+dLyA82f1iqrqVT1/QyQgBBnk9tQSPF5f7YQbQB5NaiuQrayY1S33/s5pJG7JTY="
