version: "~> 1.0"
git:
    depth: 1
    quiet: true
language: java
jdk:
    - openjdk21
branches:
    only:
        - develop
        - support/4.1
cache:
    directories:
        - "$HOME/.m2"
notifications:
    slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
    - mkdir -p $HOME/.m2
    - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
    - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
    - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
    global:
        - secure: "FGYpi+MF+Kfm5xJGdu+YrqYc+SvBESqGjeRH6EuQOLjjsKoTWzXG5pCGqKbfFCY9gdr8gA7JjEcbNPG4svBoOE19Jbasc2cjA6Dqd/o94jHSvQJpoBZ8rcGW4kshVSw1+74xgvgKlWBRckXNZntgJjz4thc3L9HCPQpAAJrvA6OrNjYPMYWNOeK6e16Z5TqqgcjLaRRrM+eTJWXOrBopEq8Jr2RDumyp2ERxZxO8C7fSk1BVSDZmOIk4RgilTVe5X3K+kS3Zmo5StqySvyvd27celvH8A88VQ7EJbyKetVZatnMDQLcGrADW2NCFkdmRQJbHK48ahFrQSVOMhTpI1NH0OJl4Nu1jqNylhCeweu4t9tzc+N8H4aBEeiKBM31bc8qRe9HIttzQmPOX+NOKTTur6XyO0lFGQ0FrzWRSbSxPq4n5ZERIqaiOwout3pGLTzJCIqJMD8SYazNo37MwtfQahqwvfCR5XoEaMSDi8YBOIuf9LrXXeH6mCg6oh32VnLlukAWABSUdf0MTbVtyKuVM1US4DhflzcPgdL15a7D6Aw6yLeIsq61BTUbJ2e3Rni3F2M7vF7u9IrN7gNoQz8fhc6jJaF71esNIhWlok/IUT4zbeeXDVANrM40kVEiUqynVwGO09vlxvphEF1xKDiv3wj/W+YefnqLDbIQ3NqA="
        - secure: "kdencKHC2oYIojYN3o9mZFFfc073MrTQ7pn2ufCZ6T8/rTWVK262GJA795+dhDeGSTGMXxayzSJS2x/KKnrg4ELfWMLPGxsHwpnN3Ank4nsq8mNmYmdwCOe3IipDfjs3MRdmrAvBP1q9ph6asvhHdCdIh/nii+pv+3hpYVn0VUUw0z+U2/phui9zqoMWdgd7qt7O7YEKAzX+EGwwMoaFzFem4Uti/kY5MCpq1MM5jt/P2XrG/G7kHifI/2cclKC5utKq6xENx+eHFTuam75r/X62ylXRUy9dOkbUznqrkYisT7qJ8sin2/+LtZgaD/QaHBwSVELalr1W88OHDl3dR8IwCENhJFwL2oRok2GjKYftUrZehD1b6TOpAkNem/npNBliRf90Gih/yro3lAzqxaM8V6dhm1vPXfQ+7iB7RzcMmetYXRKbRH3ManR4mvnsFBht8K2S7mApE5CoXa2P++QkPal/cFUZ4YUbpecqeDukMEN8O3XwlSMbCq/AhkGSqATPxWd3Ef3HV6smtFYOH5N/9e2Xo9iKBynKtWoREA5kSOE2+NlQU46uHsoR2ouVzQXMb4JoZMlhaKdZGV6RNNUDHA6htGsSmf9LM3CaXkclmuMpAX3BAzOc6AgB15CHOkMti8W8TohoSI84MFTbuO3v1IqwBJci+OpPeZ9MTrE="
