version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk21
branches:
  only:
    - develop
    - support/4.x
cache:
  directories:
  - "$HOME/.m2"
notifications:
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
  - mkdir -p $HOME/.m2
  - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
  global:
    - secure: "Epy7Nig8WriI7toRI948sHQYyhlK2Zy6YNMh904tlCtiTV/o5JDQARPHzNbImP0sw64rMtIWQB4IFxymHSoSXmhpM98UBilx2qfXurHy2+LIdDHWenweoEFt1FaWVlxgkbTu6rRNJVfUdT8TvT8wQaKZ5eJEveWaogvI13erFnvoRx5lqBE7lASIYbTI8WudICe+k1E1plyOVJ4cYWOpPE5H9cCkHwkLKZ6viOst34KZT8dudIhh7cFvERB1r0nV9TPo5d5SiwrcUqg9+iMv/Uh3fpAMj0JcX6hDtyBgzmfGDP0yzGAzl20v1+TAHWq8WQYTP2q9Aq5D4S8UJ2ggYwAAP21FRo7/msSKPoFU34wpmzPmYSPYWQGLcoLJdAMqpAKdMJU8nIGxHThyr677JSQ9WD6Ui5pkq+7+9Rkdj8yZmnG0PB0gZybmxqTA9eXaKqE0X8MQUrJ0Q/nZO5aPGwD4XLP+BhWJM2uIph3/VsuKNTjw26vkpJq2acw48hSxTmr/ETLlOjqfZaCRzF0IgG4QbfiuTjO7zgBs/BhYiQ7R6SjfksvTY6HSX3zgYhd6c7S/T4jOHoC/Gl7g3jzebHD6JCfaW0NR7Oo/zkmDf2dBDLV9amqRP8vTaoGaojciJvw+ymAwo5YBdLUC6a7Ylrv8ghhCbuzTQWy553krFgI="
    - secure: "YBvU/dp7g+wLdD1Vh1o4VpFrnfX09bemKpZQlhqbDTxhtU5VdtGgdKPal1hz/ptlSS/FtdVOty75I2sDDPh3TccNugZYFw4zCuEURM80+UpeHgRgB01bAdR/HdcX9mMsC9Cg/3eFIsE7Qv616u7CFy9zcmEBHnbtl1ZwA2fVynhuFeRD5StsTH7+kwe2V8mitikzZN9cPhMS4BXL+Sxmepzf23QAai+0Gy1hs5T3+kKpm9f8r90hUzeyRx68w0ewcfiRYCTsEFOgD96rH5lIgh6fz7fFzMUaDuECgqOCU2IRFiX4sXtLHmAb5yHIsx7oN/LjDGjZnk1rKFQ9zmVGpwGxoLUi0+DAukB1Z9EeY2pu1gr8LlKdGK/siQAQmwD0GeFGxv1zL1M0CGvvesmhIusPCMDj2rLinCZe63lc69Yn3Ort7dC7WVl0YneNK7B+wykJbcJV2wSrj0xaB8qxM0uLgXFvZlVO1nDYRz5oDgstGyUAWinSWre3AMbKy9CteGOO0KhNoASDTPzd2olMd8kiABL4lIouF6ICSJUV/cJKWqhWvcjNNYXzBHsNsR4WxFIZaaTMd4wv3R2mq+BtmRKBVX9/EAGme8A+hPgyB57wzdq8Hra4fE0UUJLZNmF9JZXS4+G2pG6zsSnvxGs2VCl0LtmATtvVNoXweeaTQIs="
